### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by izzy** [izzy/d3coder#24]
Since #23 added the capabilities of translating the extension it would be great to have more translations available for those who aren't native English speakers.

The translations need a folder with the language code in the `_locales` folder and a `messages.json` in that sub-folder. The easiest way to get all the messages is to copy the English folder(`_locales/en/`) and go from there.

Some translations might not need all the fields if e.g. the text is understandable in your language and might only need a translation in languages that use non-latin characters and have their own words/phrases for messages that are otherwise not translated. Messages that aren't translated will take their text from the English translation - see German as an example for that. 

A list of possible translations is available at https://developer.chrome.com/webstore/i18n#localeTable

I'll list translations that are done and won't be needing a translation as checked here. Those currently being worked on or free as unchecked. If it's not on the list but in the possible translation list - see link above - just write a comment under this issue, otherwise write in the linked issue so I can assign you:

- [ ] ar - Arabic #39 - possible solutions #40, #42 and #84 
- [ ] am - Amharic #72
- [x] bg - Bulgarian  #45
- [x] bn - Bengali - #73
- [ ] ca - Catalan #46
- [x] cs - Czech #47
- [x] da - Danish #48
- [x] de - German
- [x] el - Greek
- [x] en - English
- [x] es - Spanish
- [ ] et - Estonian #49
- [ ] fa - Persian #74
- [x] fi - Finnish #50
- [ ] fil - Filipino #51
- [x] fr - French
- [ ] he - Hebrew #52
- [x] hi - Hindi #53
- [x] hr - Croatian #54
- [x] hu - Hungarian #55
- [x] id - Indonesian #56
- [x] it - Italian #57
- [x] ja - Japanese #58
- [x] kn - Kannada #75
- [x] ko - Korean #59
- [x] nl - Dutch
- [x] pl - Polish
- [x] pt_BR - Portuguese - Brazil
- [x] ru - Russian
- [x] tr - Turkish
- [x] uk - Ukrainian #77 
- [x] zh_CN - Chinese (China) #60
- [x] zh_TW - Chinese (Taiwan) #61

**Comment by thalesagapito** [comment]
I can help out with pt-BR!

**Comment by EhrenfeldN** [comment]
Hi @izzy , I can translate into French if needed!

**Comment by peakercope** [comment]
hello @izzy 
I can help with Russian translation

**Comment by izzy** [comment]
@peakercope great! please open a simple issue(see #33 as example), i'll add it to the list uptop :)

**Comment by murtajaziad** [comment]
Hello @izzy , I can work on Arabic translation if needed!

**Comment by toyamarodrigo** [comment]
Hello @izzy , I can work on Spanish translation if not taken!

**Comment by Pervolarakis** [comment]
hey @izzy i can translate to greek if needed

**Comment by gaurav219** [comment]
Hey @izzy , I'll go with the korean translation, if not taken??

**Comment by izzy** [comment]
@gaurav219 Sure, if you comment in the linked issue I can assign it to you! :)

**Comment by Syarol** [comment]
Hello @izzy, can I translate into Ukrainian?

**Comment by sk6298** [comment]
Hi @izzy , Can I go for (#75) issue ?

**Comment by izzy** [comment]
@Syarol sure, I've added #77 for you, if you comment there I can assign it :)

**Comment by YousofMersal** [comment]
Mind me taking a swing at the Danish translation? :)

**Comment by GriffinMLN** [comment]
@izzy please assign me to "Add Bulgarian translation #45 "

**Comment by krisfremen** [comment]
Hi @izzy ,

I'd like to translate into a new language, Macedonian (mk).

Cheers!

**Comment by izzy** [comment]
@krisfremen I'm sorry but afaics that's not language supported by Chrome/Blink-based browsers(see the link in the issue text, paragraph "Choosing locales to support") so it wouldn't make much sense to have it since it would never really show up anywhere. :/

**Comment by batistaleandro** [comment]
Hi @izzy,

I added PT_pt translations.

**Comment by akshaythakare7** [comment]
Hey @izzy, I am on Marathi (mr) translations ..
